-- GENERATED FILE - DO NOT EDIT.
-- Generated by tools/make-baseline.mjs from the live database public schema.
-- Generated on: 2026-10-07
-- Regenerate with: npm run db:baseline:generate

SET check_function_bodies = off;
SET search_path = public;

-- ==== section: enums ====
CREATE TYPE public.game_status AS ENUM ('pending', 'active', 'completed');
CREATE TYPE public.game_team AS ENUM ('team_a', 'team_b');
CREATE TYPE public.game_winner AS ENUM ('team_a', 'team_b');
CREATE TYPE public.host_request_status AS ENUM ('pending', 'approved', 'denied');
CREATE TYPE public.queue_entry_status AS ENUM ('waiting', 'marked_out', 'removed');
CREATE TYPE public.rotation_style AS ENUM ('winner_stays', 'rotate_all');
CREATE TYPE public.run_mode AS ENUM ('score_only', 'queue_only', 'score_and_queue');
CREATE TYPE public.run_status AS ENUM ('lobby', 'active', 'completed');

-- ==== section: tables ====
CREATE TABLE public.courts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  run_id uuid NOT NULL,
  number integer NOT NULL,
  name text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.game_players (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  game_id uuid NOT NULL,
  queue_entry_id uuid NOT NULL,
  team public.game_team NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.games (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  run_id uuid NOT NULL,
  game_number integer NOT NULL,
  status public.game_status DEFAULT 'pending'::public.game_status NOT NULL,
  score_goal integer NOT NULL,
  score_a integer DEFAULT 0 NOT NULL,
  score_b integer DEFAULT 0 NOT NULL,
  winner public.game_winner,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  court_id uuid NOT NULL
);
CREATE TABLE public.host_requests (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  status public.host_request_status DEFAULT 'pending'::public.host_request_status NOT NULL,
  note text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  decided_at timestamp with time zone,
  display_name text NOT NULL
);
CREATE TABLE public.invites (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  email text NOT NULL,
  token text NOT NULL,
  used_at timestamp with time zone,
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval) NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.queue_entries (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  run_id uuid NOT NULL,
  user_id uuid,
  display_name text NOT NULL,
  status public.queue_entry_status DEFAULT 'waiting'::public.queue_entry_status NOT NULL,
  joined_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  position integer NOT NULL,
  paid boolean DEFAULT false NOT NULL
);
CREATE TABLE public.runs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  host_id uuid NOT NULL,
  name text NOT NULL,
  location text,
  status public.run_status DEFAULT 'lobby'::public.run_status NOT NULL,
  session_code text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  score_goal integer DEFAULT 11 NOT NULL,
  run_mode public.run_mode DEFAULT 'score_and_queue'::public.run_mode NOT NULL,
  rotation_style public.rotation_style DEFAULT 'rotate_all'::public.rotation_style NOT NULL,
  court_count integer DEFAULT 1 NOT NULL,
  win_by_two boolean DEFAULT false NOT NULL
);
CREATE TABLE public.score_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  game_id uuid NOT NULL,
  queue_entry_id uuid NOT NULL,
  team public.game_team NOT NULL,
  voided_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  points integer DEFAULT 1 NOT NULL
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  display_name text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  welcome_sent_at timestamp with time zone
);

-- ==== section: functions ====
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    BEGIN
      INSERT INTO public.users (id, display_name)
      VALUES (
        NEW.id,
        COALESCE(
          NEW.raw_user_meta_data->>'displayName',
          split_part(NEW.email, '@', 1),
          'Player'
        )
      )
      ON CONFLICT (id) DO NOTHING;
      RETURN NEW;
    END;
    $function$;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.rotate_queue_on_game_complete()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    DECLARE
      v_run_mode       run_mode;
      v_rotation_style rotation_style;
      v_max_pos        integer;
    BEGIN
      IF NEW.status <> 'completed' OR OLD.status = 'completed' THEN
        RETURN NEW;
      END IF;

      SELECT run_mode, rotation_style INTO v_run_mode, v_rotation_style
      FROM public.runs WHERE id = NEW.run_id;

      IF v_run_mode = 'score_only' THEN
        RETURN NEW;
      END IF;

      PERFORM pg_advisory_xact_lock(hashtext(NEW.run_id::text), 2);

      SELECT COALESCE(MAX(position), 0) INTO v_max_pos
      FROM public.queue_entries
      WHERE run_id = NEW.run_id AND status <> 'removed';

      WITH to_rotate AS (
        SELECT gp.queue_entry_id, gp.team, qe.position AS old_pos
        FROM public.game_players gp
        JOIN public.queue_entries qe ON qe.id = gp.queue_entry_id
        WHERE gp.game_id = NEW.id
          AND qe.status <> 'removed'
          AND (
            NEW.winner IS NULL
            OR v_rotation_style = 'rotate_all'
            OR (v_rotation_style = 'winner_stays' AND gp.team::text <> NEW.winner::text)
          )
      ),
      ranked AS (
        SELECT queue_entry_id,
               v_max_pos + ROW_NUMBER() OVER (
                 ORDER BY
                   CASE
                     WHEN NEW.winner IS NOT NULL AND v_rotation_style = 'rotate_all'
                       THEN (team::text <> NEW.winner::text)
                     ELSE FALSE
                   END ASC,
                   old_pos ASC
               ) AS new_pos
        FROM to_rotate
      )
      UPDATE public.queue_entries qe
      SET position = ranked.new_pos, updated_at = NOW()
      FROM ranked
      WHERE qe.id = ranked.queue_entry_id;

      RETURN NEW;
    END;
    $function$;

CREATE OR REPLACE FUNCTION public.stamp_host_request_decision()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    BEGIN
      IF OLD.status = 'pending' AND NEW.status IN ('approved', 'denied') THEN
        NEW.decided_at = now();
      END IF;
      RETURN NEW;
    END;
    $function$;

CREATE OR REPLACE FUNCTION public.sync_game_score()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    DECLARE
      v_game_id uuid;
    BEGIN
      v_game_id := COALESCE(NEW.game_id, OLD.game_id);

      UPDATE public.games
      SET
        score_a = (
          SELECT COALESCE(SUM(points), 0) FROM public.score_events
          WHERE game_id = v_game_id
            AND team = 'team_a'
            AND voided_at IS NULL
        ),
        score_b = (
          SELECT COALESCE(SUM(points), 0) FROM public.score_events
          WHERE game_id = v_game_id
            AND team = 'team_b'
            AND voided_at IS NULL
        ),
        updated_at = NOW()
      WHERE id = v_game_id;

      RETURN NEW;
    END;
    $function$;


-- ==== section: constraints ====
ALTER TABLE public.courts ADD CONSTRAINT courts_pkey PRIMARY KEY (id);
ALTER TABLE public.game_players ADD CONSTRAINT game_players_pkey PRIMARY KEY (id);
ALTER TABLE public.games ADD CONSTRAINT games_pkey PRIMARY KEY (id);
ALTER TABLE public.host_requests ADD CONSTRAINT host_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.invites ADD CONSTRAINT invites_pkey PRIMARY KEY (id);
ALTER TABLE public.queue_entries ADD CONSTRAINT queue_entries_pkey PRIMARY KEY (id);
ALTER TABLE public.runs ADD CONSTRAINT runs_pkey PRIMARY KEY (id);
ALTER TABLE public.score_events ADD CONSTRAINT score_events_pkey PRIMARY KEY (id);
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE public.courts ADD CONSTRAINT uq_courts_run_id_number UNIQUE (run_id, number);
ALTER TABLE public.courts ADD CONSTRAINT courts_number_check CHECK ((number >= 1));
ALTER TABLE public.runs ADD CONSTRAINT runs_court_count_check CHECK ((court_count >= 1));

-- ==== section: foreign-keys ====
ALTER TABLE public.courts ADD CONSTRAINT courts_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;
ALTER TABLE public.game_players ADD CONSTRAINT game_players_game_id_games_id_fk FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;
ALTER TABLE public.game_players ADD CONSTRAINT game_players_queue_entry_id_queue_entries_id_fk FOREIGN KEY (queue_entry_id) REFERENCES public.queue_entries(id) ON DELETE RESTRICT;
ALTER TABLE public.games ADD CONSTRAINT games_court_id_fkey FOREIGN KEY (court_id) REFERENCES public.courts(id) ON DELETE RESTRICT;
ALTER TABLE public.games ADD CONSTRAINT games_run_id_runs_id_fk FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;
ALTER TABLE public.host_requests ADD CONSTRAINT host_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.queue_entries ADD CONSTRAINT queue_entries_run_id_runs_id_fk FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;
ALTER TABLE public.queue_entries ADD CONSTRAINT queue_entries_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.runs ADD CONSTRAINT runs_host_id_users_id_fk FOREIGN KEY (host_id) REFERENCES public.users(id) ON DELETE RESTRICT;
ALTER TABLE public.score_events ADD CONSTRAINT score_events_game_id_games_id_fk FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;
ALTER TABLE public.score_events ADD CONSTRAINT score_events_queue_entry_id_queue_entries_id_fk FOREIGN KEY (queue_entry_id) REFERENCES public.queue_entries(id) ON DELETE RESTRICT;
ALTER TABLE public.users ADD CONSTRAINT users_id_fk FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- ==== section: indexes ====
CREATE INDEX idx_courts_run_id ON public.courts USING btree (run_id);
CREATE INDEX idx_game_players_game_id ON public.game_players USING btree (game_id);
CREATE INDEX idx_game_players_queue_entry_id ON public.game_players USING btree (queue_entry_id);
CREATE UNIQUE INDEX uq_game_players_game_entry ON public.game_players USING btree (game_id, queue_entry_id);
CREATE INDEX idx_games_court_id ON public.games USING btree (court_id);
CREATE INDEX idx_games_run_id ON public.games USING btree (run_id);
CREATE INDEX idx_games_status ON public.games USING btree (status);
CREATE UNIQUE INDEX uq_games_court_open ON public.games USING btree (court_id) WHERE (status = ANY (ARRAY['pending'::public.game_status, 'active'::public.game_status]));
CREATE UNIQUE INDEX uq_games_run_id_game_number ON public.games USING btree (run_id, game_number);
CREATE INDEX idx_host_requests_user_id ON public.host_requests USING btree (user_id);
CREATE UNIQUE INDEX uq_host_requests_one_pending ON public.host_requests USING btree (user_id) WHERE (status = 'pending'::public.host_request_status);
CREATE INDEX idx_invites_lower_email ON public.invites USING btree (lower(email));
CREATE UNIQUE INDEX uq_invites_token ON public.invites USING btree (token);
CREATE INDEX idx_queue_entries_run_id ON public.queue_entries USING btree (run_id);
CREATE INDEX idx_queue_entries_run_id_position ON public.queue_entries USING btree (run_id, "position");
CREATE INDEX idx_queue_entries_user_id ON public.queue_entries USING btree (user_id);
CREATE INDEX idx_runs_host_id ON public.runs USING btree (host_id);
CREATE INDEX idx_runs_status ON public.runs USING btree (status);
CREATE UNIQUE INDEX uq_runs_one_open_per_host ON public.runs USING btree (host_id) WHERE (status = ANY (ARRAY['lobby'::public.run_status, 'active'::public.run_status]));
CREATE UNIQUE INDEX uq_runs_session_code ON public.runs USING btree (session_code);
CREATE INDEX idx_score_events_game_id ON public.score_events USING btree (game_id);
CREATE INDEX idx_score_events_game_voided ON public.score_events USING btree (game_id) WHERE (voided_at IS NULL);
CREATE INDEX idx_score_events_queue_entry_id ON public.score_events USING btree (queue_entry_id);
CREATE INDEX idx_users_created_at ON public.users USING btree (created_at);

-- ==== section: row-level-security ====
ALTER TABLE public.courts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.host_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.queue_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.score_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- ==== section: policies ====
CREATE POLICY courts_select ON public.courts AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY game_players_insert ON public.game_players AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1
   FROM (public.games g
     JOIN public.runs r ON ((r.id = g.run_id)))
  WHERE ((g.id = game_players.game_id) AND (r.host_id = auth.uid())))));
CREATE POLICY game_players_select ON public.game_players AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY games_insert ON public.games AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1
   FROM public.runs
  WHERE ((runs.id = games.run_id) AND (runs.host_id = auth.uid())))));
CREATE POLICY games_select ON public.games AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY games_update ON public.games AS PERMISSIVE FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.runs
  WHERE ((runs.id = games.run_id) AND (runs.host_id = auth.uid()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM public.runs
  WHERE ((runs.id = games.run_id) AND (runs.host_id = auth.uid())))));
CREATE POLICY host_requests_insert_own ON public.host_requests AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((user_id = auth.uid()) AND (status = 'pending'::public.host_request_status)));
CREATE POLICY host_requests_select_own ON public.host_requests AS PERMISSIVE FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY queue_entries_select ON public.queue_entries AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY queue_entries_update ON public.queue_entries AS PERMISSIVE FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.runs
  WHERE ((runs.id = queue_entries.run_id) AND (runs.host_id = auth.uid()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM public.runs
  WHERE ((runs.id = queue_entries.run_id) AND (runs.host_id = auth.uid())))));
CREATE POLICY runs_insert ON public.runs AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((host_id = auth.uid()));
CREATE POLICY runs_select_anon ON public.runs AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY runs_select_authenticated ON public.runs AS PERMISSIVE FOR SELECT TO authenticated USING (((host_id = auth.uid()) OR (EXISTS ( SELECT 1
   FROM public.queue_entries
  WHERE ((queue_entries.run_id = runs.id) AND (queue_entries.user_id = auth.uid()))))));
CREATE POLICY runs_update ON public.runs AS PERMISSIVE FOR UPDATE TO authenticated USING ((host_id = auth.uid())) WITH CHECK ((host_id = auth.uid()));
CREATE POLICY score_events_insert ON public.score_events AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1
   FROM (public.games g
     JOIN public.runs r ON ((r.id = g.run_id)))
  WHERE ((g.id = score_events.game_id) AND (r.host_id = auth.uid())))));
CREATE POLICY score_events_select ON public.score_events AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY score_events_update ON public.score_events AS PERMISSIVE FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1
   FROM (public.games g
     JOIN public.runs r ON ((r.id = g.run_id)))
  WHERE ((g.id = score_events.game_id) AND (r.host_id = auth.uid()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM (public.games g
     JOIN public.runs r ON ((r.id = g.run_id)))
  WHERE ((g.id = score_events.game_id) AND (r.host_id = auth.uid())))));
CREATE POLICY users_select_own ON public.users AS PERMISSIVE FOR SELECT TO authenticated USING ((auth.uid() = id));
CREATE POLICY users_update_own ON public.users AS PERMISSIVE FOR UPDATE TO authenticated USING ((auth.uid() = id)) WITH CHECK ((auth.uid() = id));

-- ==== section: triggers ====
CREATE TRIGGER trg_rotate_queue_on_game_complete AFTER UPDATE OF status ON public.games FOR EACH ROW EXECUTE FUNCTION public.rotate_queue_on_game_complete();
CREATE TRIGGER trg_stamp_host_request_decision BEFORE UPDATE OF status ON public.host_requests FOR EACH ROW EXECUTE FUNCTION public.stamp_host_request_decision();
CREATE TRIGGER trg_score_events_update_game_score AFTER INSERT OR UPDATE OF voided_at ON public.score_events FOR EACH ROW EXECUTE FUNCTION public.sync_game_score();

-- ==== section: auth-triggers ====
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==== section: replica-identity ====
ALTER TABLE public.courts REPLICA IDENTITY FULL;

-- ==== section: realtime-publication ====
DO $baseline$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
    AND NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'courts') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.courts;
  END IF;
END
$baseline$;
DO $baseline$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
    AND NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'games') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.games;
  END IF;
END
$baseline$;
DO $baseline$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
    AND NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'queue_entries') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.queue_entries;
  END IF;
END
$baseline$;
DO $baseline$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
    AND NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'runs') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.runs;
  END IF;
END
$baseline$;
